name: ZombieRider
version: ${project.version}
main: me.prostedeni.goodcraft.zombierider.ZombieRider
api-version: 1.13
description: plugin that allows you to ride all hostile mobs
commands:
  zombierider:
    description: lets you reload config of ZombieRider
